### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by corentin-larose**
Couple of optimization on the most call intensive functions.

The isset change is far less important than the array_map one which saves ~50% of time on the examples/bayes.php script.

(Even if I must admit this is very ugly.....)

### CODE REVIEW

**Comment by camspiers** [comment]
Thanks heaps for this. It is a great fix. I wonder if we should do it the following way:

We could change the API to make it so the normalization can operate on strings as well as arrays. Then we can change it to do the normalization before the tokenization occurs, which would mean we don't need to do the implode and the explode.

What are your thoughts?

**Comment by corentin-larose** [comment]
Yes, being able to normalize either at "document stage" or at "token stage" could be great (typically, you can't stem at document stage), my fix was only a matter of quick-fix.

So I imagine we could do something like:

``` php
foreach ($data as $category => $documents) {
            $transform[$category]  = array();
            foreach ($documents as $document) {
                $transform[$category][] = array_count_values(
                    $this->normalizer->normalizeTokens(
                        $this->tokenizer->tokenize(
                            $this->normalizer->normalizeDocument(
                                $document
                            )
                        )
                    )
                );
            }
        }
```

**Comment by camspiers** [comment]
What do you think about this? https://github.com/camspiers/statistical-classifier/compare/qapa-optimization

**Comment by camspiers** [comment]
I really like the splitting of the normalizers by token and document. I think we should combine together what you have done on the splitting and I have done by pulling out the token preparation into a transform. Thoughts?

**Comment by corentin-larose** [comment]
Sounds great!
Thanks for your trust!

Ok, here is my point for what it is worth...

Let's take the stem normalizer as an interesting example, there's no point having a "document stemmer", since you can only stem a token thus, I think that we should split normalizers in two contracts:
    - an interface for a document which operates on strings, 
    - an interface for tokens which operates on arrays.

Since Lowercase normalizers was the default normalizer, if we choose to lowercase at document stage, then, we must had a Base/Default normalizer which does... nothing.

Since the whole is a BC break and I'm pretty sure that I'm not the only guy thinking that your work is amazing thus using it, IMHO we should at least bump to 0.8.0 version.

Here is my proposal for this purpose, (a lot of diff cause of the normalizers moving into a new directory) https://github.com/qapa/statistical-classifier/commit/e071b7586e068b1b7a18cfac208427a1729c57bb

**Comment by camspiers** [comment]
We also might what to change the name of the Base token normalizer to something like `Noop`, or alternatively dropping it and and just conditionally doing the normalizing?

**Comment by camspiers** [comment]
I really like it. I definitely agree with bumping the version. I am trying my best to stick to semantic versioning and with your help and review would love to get API to 1.0.0.

**Comment by corentin-larose** [comment]
I agree about the Base normalizer.

I could make the fix, just let me know if you agree with my last CS fix (I'm using php-cs-fixer from SensioLabs as Zend framework and Symfony  do).

I also am going to swap my origin with the canonical since you kindly allowed me.

**Comment by camspiers** [comment]
Doing the CS Fix is really good. I even have the config file setup: https://github.com/camspiers/statistical-classifier/blob/master/.php_cs

If you could, I would like to try keep the commit history as clean as possible. So when there is opportunity to squash commits that haven't yet got to origin/master and are now superseded, I would like to squash them.

**Comment by corentin-larose** [comment]
Ok, since you agree with CS, I'm going to squash the last one.
Did the same for the examples PR.
Will also make the change you suggested about the base token normalizer.
My Skype: corentin.larose

**Comment by corentin-larose** [comment]
Squashed!

**Comment by camspiers** [comment]
Hmm, looks like the Stopword test is failing.

**Comment by corentin-larose** [comment]
- removed base normalizer
- fixed U.T

Note that I changed the TokenCountByDocument params order in order to be able to pass no document normalizer (a tokenizer is mandatory). If you don't like it, I revert!

**Comment by corentin-larose** [comment]
I just saw your" I think we should combine together what you have done on the splitting and I have done by pulling out the token preparation into a transform. Thoughts?" I missed it, seems we posted at the same time!

Yes, I think it could be good, plus, I'm writing a summary about the different information states to be sure not to miss the point... I'm pretty new to your code!

Have to take a train will be back around 11PM UTC.

**Comment by camspiers** [comment]
In order to merge this I am going to do some refactoring because of the change I have made on master since.

**Comment by camspiers** [comment]
Merged https://github.com/camspiers/statistical-classifier/commit/ebb94bdbf47af66c7bcc30b47bc87acf1228b1d2

Thanks heaps for these changes. Better performance and a step closer to a better API

**Pull request merged**
