### PR TITLE
New stemmer normalizer

### PR DESCRIPTION
**Pull request by corentin-larose**
A fast stemmer based on php-stemmer extension

### CODE REVIEW

**Comment by camspiers** [comment]
I like this. I think that maybe we should valid the language and throw an exception if it isn't in the list.

**Comment by camspiers** [comment]
Merged via https://github.com/camspiers/statistical-classifier/commit/743c6464a11f3b89925cc1308ec9a8de6dd9b931

Thanks, this is a nice addition. Next step is to get php-stemmer available via homebrew :)

**Comment by camspiers** [comment]
The invalid language exception can be added later if you think it is a good idea.

**Comment by corentin-larose** [comment]
Yes, this is a good idea to add an exception, not sure whether the component itself alreadydoes that, gonna make a couple of tests and correct this.

If you are working on Zend Server (I am, on Ubuntu):

git clone https://github.com/hthetiot/php-stemmer.git /tmp/phpstemmer
cd /tmp/phpstemmer
/usr/local/zend/bin/phpize
./configure
sudo make -C libstemmer_c
sudo make && sudo make install
echo "extension=stemmer.so" | sudo tee -a /usr/local/zend/etc/conf.d/stemmer.ini
sudo chown root:zend /usr/local/zend/etc/conf.d/stemmer.ini
sudo chmod 0664 /usr/local/zend/etc/conf.d/stemmer.ini
sudo /usr/local/zend/bin/zendctl.sh restart
sudo rm -rf /tmp/phpstemmer

**Comment by camspiers** [comment]
I made a PR to homebrew php for os x users: https://github.com/josegonzalez/homebrew-php/pull/950

**Pull request closed without merging**
