### PR TITLE
Typo fix in examples bootstrap path

### PR DESCRIPTION
**Pull request by corentin-larose**

### CODE REVIEW

**Comment by camspiers** [comment]
The paths should actually be:

`require_once __DIR__ . '/../vendor/autoload.php';`

Keen to change it? :)

**Comment by camspiers** [comment]
The current path is something that I missed when I refactored things some time ago.

**Comment by corentin-larose** [comment]
Indeed ! should have figured out, I just looked for a bootstrap like a dummy :D Sorry for that...

**Comment by corentin-larose** [comment]
Fixed

**Comment by camspiers** [comment]
Sorry for the annoyance, but could you squash your commits? http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by camspiers** [comment]
Merged via https://github.com/camspiers/statistical-classifier/pull/17

**Pull request closed without merging**
