### PR TITLE
Syntax highlighting was missing in one of the examples (README)

### PR DESCRIPTION
**Pull request by khromov**

### CODE REVIEW

**Comment by camspiers** [comment]
I'll merge this, but can I get you to rebase the commits so the PECLStem work doesn't appear in the history?

**Comment by khromov** [comment]
Hi cam,

The rebase didn't seem to take once I pushed it to Github, so I made a new pull request. #11

**Comment by camspiers** [comment]
@khromov Thanks for the change. Were you using the `-f` force flag when pushing? If not, that probably would have fixed the issue.

**Comment by khromov** [comment]
I didn't use that flag. Thanks for the tip. :+1:

**Pull request closed without merging**
